=== 203956/PKCK5/PKCK5/Resources/secondExercise.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema elementFormDefault="qualified"
           targetNamespace="http://www.example.org/types"
           xmlns:type="http://www.example.org/types"
           xmlns:xs="http://www.w3.org/2001/XMLSchema">  
    
    <xs:complexType name="dokumentType">
        <xs:sequence>
            <xs:element name="nagłówek" type="type:nagłówekType" minOccurs="1" maxOccurs="1"/>
            <xs:element name="biblioteka" type="type:bibliotekaType" minOccurs="1" maxOccurs="unbounded">
                <xs:key name="działKey">
                    <xs:selector xpath="type:działy/type:dział"/>
                    <xs:field xpath="@id"/>
                </xs:key>
                <xs:keyref name="działRef" refer="type:działKey">
                    <xs:selector xpath="type:dany_dział"/>
                    <xs:field xpath="@id_działu"/>
                </xs:keyref>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
    
    <xs:complexType name="nagłówekType">
        <xs:sequence>
            <xs:element name="opis" type="xs:string" minOccurs="1" maxOccurs="1"/>
            <xs:element name="autorzy_dokumentu" type="type:autorzy_dokumentuType" minOccurs="1" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>
    
    <xs:complexType name="autorzy_dokumentuType">
        <xs:sequence>
            <xs:element name="autor_dokumentu" type="type:autor_dokumentuType" minOccurs="2" maxOccurs="2"/>
        </xs:sequence>
    </xs:complexType>
    
    <xs:complexType name="autor_dokumentuType">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute name="indeks" use="required" type="type:indeksType"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>
    
    <xs:simpleType name="indeksType">
        <xs:restriction base="xs:positiveInteger">
            <xs:pattern value="[1-9][0-9][0-9][0-9][0-9][0-9]"/>
        </xs:restriction>
    </xs:simpleType>
    
    <xs:complexType name="bibliotekaType">
        <xs:sequence>
            <xs:element name="nazwa" type="xs:string"/>
            <xs:element name="adres" type="type:adresType"/>
            <xs:element name="działy" type="type:działyType"/>
            <xs:element name="dany_dział" type="type:dany_działType" minOccurs="1" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>
    
    <xs:complexType name="adresType">
        <xs:sequence>
            <xs:element name="ulica" type="xs:string"/>
            <xs:element name="numer" type="xs:string"/>
            <xs:element name="miejscowość" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>
    
    <xs:complexType name="działyType">
        <xs:sequence>
            <xs:element name="dział" type="type:działType" minOccurs="1" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>
    
    <xs:attributeGroup name="id_nazwa_attr">
        <xs:attribute name="id" use="required" type="type:idType"/>
        <xs:attribute name="nazwa_działu" use="required" type="type:nazwa_działuType"/>
    </xs:attributeGroup>
    
    <xs:simpleType name="idType">
        <xs:restriction base="xs:string">
            <xs:length value="2"/>
            <xs:pattern value="[a-z][a-z]"/>
        </xs:restriction>
    </xs:simpleType>
    
    <xs:simpleType name="nazwa_działuType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="dla_dzieci"/>
            <xs:enumeration value="dla_młodzieży"/>
            <xs:enumeration value="horror"/>
            <xs:enumeration value="fantasy"/>
            <xs:enumeration value="biografia"/>
            <xs:enumeration value="popularnonaukowe"/>
        </xs:restriction>
    </xs:simpleType>
    
    <xs:complexType name="działType">
        <xs:attributeGroup ref="type:id_nazwa_attr"/>
    </xs:complexType>
    
    <xs:complexType name="dany_działType">
        <xs:all>
            <xs:element name="książki" type="type:książkiType" minOccurs="0"/>
        </xs:all>
        <xs:attribute name="id_działu" use="required" type="type:idType"/>
    </xs:complexType>
    
    <xs:complexType name="książkiType">
        <xs:sequence>
            <xs:element name="książka" type="type:książkaType" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>
    
    <xs:complexType name="książkaType">
        <xs:sequence>
            <xs:element name="tytuł" type="xs:string" minOccurs="1" maxOccurs="1"/>
            <xs:element name="autorzy" type="type:autorzyType" minOccurs="1" maxOccurs="1"/>
            <xs:element name="ilość_stron" type="xs:positiveInteger" minOccurs="1" maxOccurs="1"/>
            <xs:element name="data_wydania" type="type:data_wydaniaType" minOccurs="0" maxOccurs="1"/>
        </xs:sequence>
        <xs:attribute name="id" use="required" type="type:id_książkaType"/>
    </xs:complexType>
    
    <xs:simpleType name="id_książkaType">
        <xs:restriction base="xs:string">
            <xs:pattern value="[0-9][0-9][0-9]"/>
        </xs:restriction>
    </xs:simpleType>
    
    <xs:complexType name="autorzyType">
        <xs:sequence>
            <xs:element name="autor" type="type:autorType" minOccurs="1" maxOccurs="3"/>
        </xs:sequence>
    </xs:complexType>
    
    <xs:complexType name="autorType">
        <xs:attribute name="nazwa_autora" use="required" type="type:nazwa_autoraType"/>
    </xs:complexType>
    
    <xs:simpleType name="nazwa_autoraType">
        <xs:restriction base="xs:token">
            <xs:enumeration value="Magdalena_Tulli"/>
            <xs:enumeration value="Marek_Bieńczyk"/>
            <xs:enumeration value="Joanna_Bator"/>
            <xs:enumeration value="Paweł_Huelle"/>
            <xs:enumeration value="Jacek_Dukaj"/>
            <xs:enumeration value="Antoni_Libera"/>
            <xs:enumeration value="Michał_Witkowski"/>
            <xs:enumeration value="Olga_Tokarczuk"/>
            <xs:enumeration value="Wiesław_Myśliwski"/>
            <xs:enumeration value="Jakub_Żulczyk"/>
        </xs:restriction>
    </xs:simpleType>
    
    <xs:complexType name="data_wydaniaType">
        <xs:attributeGroup ref="type:data_wydaniaAttr"/>
    </xs:complexType>
    
    <xs:attributeGroup name="data_wydaniaAttr">
        <xs:attribute name="dzień" use="optional" type="type:dzieńType"/>
        <xs:attribute name="miesiąc" use="required" type="type:miesiącType"/>
        <xs:attribute name="rok" use="required" type="type:rokType"/>
    </xs:attributeGroup>
    
    <xs:simpleType name="dzieńType">
        <xs:restriction base="xs:positiveInteger">
            <xs:minInclusive value="1"/>
            <xs:maxInclusive value="31"/>
            <xs:pattern value="[0-3][0-9]"/>
        </xs:restriction>
    </xs:simpleType>
    
    <xs:simpleType name="miesiącType">
        <xs:restriction base="xs:positiveInteger">
            <xs:minInclusive value="1"/>
            <xs:maxInclusive value="12"/>
            <xs:pattern value="[0-1][0-9]"/>
        </xs:restriction>
    </xs:simpleType>
    
    <xs:simpleType name="rokType">
        <xs:restriction base="xs:positiveInteger">
            <xs:minInclusive value="1500"/>
            <xs:maxInclusive value="2018"/>
        </xs:restriction>
    </xs:simpleType>
    
    <xs:element name="dokument" type="type:dokumentType"/>
    
</xs:schema>

=== 203956/PKCK5/PKCK5/Resources/firstExercise.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet href="firstExercise.css" type="text/css"?>
<!--<!DOCTYPE dokument SYSTEM "firstExercise.dtd"[
<!ENTITY autor1 "Paweł Ograbek">
<!ENTITY autor2 "Kamil Kaźmierczak">
<!ENTITY zadanie "Zadanie 2">
]> -->

<dokument 
xmlns="http://www.example.org/types"
xmlns:xs="http://www.w3.org/2001/XMLSchema-instance" 
xs:schemaLocation="http://www.example.org/types secondExercise.xsd">
    
    <nagłówek>
        <opis>Zadanie 5</opis>
        <autorzy_dokumentu>
            <autor_dokumentu indeks="203956">
                Paweł Ograbek
            </autor_dokumentu>
            <autor_dokumentu indeks="203901">
                Kamil Kaźmierczak
            </autor_dokumentu>
        </autorzy_dokumentu>
    </nagłówek>
    
    <biblioteka>
        <nazwa>Czytaj Wszystkim!</nazwa>
        <adres>
            <ulica>Radwańska</ulica>
            <numer>124</numer>
            <miejscowość>Łódź</miejscowość>
        </adres>
        
        <działy>
            <dział id="dd" nazwa_działu="dla_dzieci" />
            <dział id="dm" nazwa_działu="dla_młodzieży" />
            <dział id="hr" nazwa_działu="horror" />
            <dział id="bg" nazwa_działu="biografia" />
            <dział id="fn" nazwa_działu="fantasy" />
            <dział id="pn" nazwa_działu="popularnonaukowe" />               
        </działy>
        
        <dany_dział id_działu="dd">
            <książki>
                <książka id="001">
                    <tytuł>Jakaś książka</tytuł>
                    <autorzy> 
                        <autor nazwa_autora="Magdalena_Tulli"/>
                        <autor nazwa_autora="Marek_Bieńczyk"/>
                    </autorzy>
                    <ilość_stron>340</ilość_stron>
                    <data_wydania dzień="05" miesiąc="04" rok="2013" />
                </książka>
                <książka id="002">
                    <tytuł>Jakaś książka 2</tytuł>
                    <autorzy> 
                        <autor nazwa_autora="Marek_Bieńczyk"/>
                    </autorzy>
                    <ilość_stron>198</ilość_stron>
                    <data_wydania dzień="11" miesiąc="12" rok="2017" />
                </książka>
                <książka id="003">
                    <tytuł>Jakaś książka 3</tytuł>
                    <autorzy> 
                        <autor nazwa_autora="Magdalena_Tulli"/>
                        <autor nazwa_autora="Marek_Bieńczyk"/>
                        <autor nazwa_autora="Joanna_Bator"/>
                    </autorzy>
                    <ilość_stron>567</ilość_stron>
                    <data_wydania dzień="01" miesiąc="01" rok="2001" />
                </książka>
            </książki>
        </dany_dział>
        
       <dany_dział id_działu="dm">
            <książki>
                <książka id="004">
                    <tytuł>Jakaś książka 4</tytuł>
                    <autorzy> 
                        <autor nazwa_autora="Michał_Witkowski"/>
                        <autor nazwa_autora="Marek_Bieńczyk"/>
                    </autorzy>
                    <ilość_stron>336</ilość_stron>
                    <data_wydania dzień="09" miesiąc="08" rok="2018" />
                </książka>
                <książka id="005">
                    <tytuł>Jakaś książka 5</tytuł>
                    <autorzy> 
                        <autor nazwa_autora="Magdalena_Tulli"/>
                        <autor nazwa_autora="Marek_Bieńczyk"/>
                        <autor nazwa_autora="Joanna_Bator"/>
                    </autorzy>
                    <ilość_stron>1258</ilość_stron>
                    <data_wydania dzień="09" miesiąc="09" rok="2017" />
                </książka>
                <książka id="006">
                    <tytuł>Jakaś książka 6</tytuł>
                    <autorzy> 
                        <autor nazwa_autora="Magdalena_Tulli"/>
                        <autor nazwa_autora="Joanna_Bator"/>
                        <autor nazwa_autora="Olga_Tokarczuk"/>
                    </autorzy>
                    <ilość_stron>1569</ilość_stron>
                    <data_wydania dzień="07" miesiąc="07" rok="2017" />
                </książka>
                <książka id="007">
                    <tytuł>Jakaś książka 7</tytuł>
                    <autorzy> 
                        <autor nazwa_autora="Joanna_Bator"/>
                        <autor nazwa_autora="Magdalena_Tulli"/>
                    </autorzy>
                    <ilość_stron>458</ilość_stron>
                    <data_wydania dzień="06" miesiąc="06" rok="2016" />
                </książka>
                <książka id="008">
                    <tytuł>Jakaś książka 8</tytuł>
                    <autorzy> 
                        <autor nazwa_autora="Paweł_Huelle"/>
                        <autor nazwa_autora="Marek_Bieńczyk"/>
                    </autorzy>
                    <ilość_stron>589</ilość_stron>
                    <data_wydania dzień="05" miesiąc="05" rok="2015" />
                </książka>
                <książka id="009">
                    <tytuł>Jakaś książka 9</tytuł>
                    <autorzy> 
                        <autor nazwa_autora="Joanna_Bator"/>
                    </autorzy>
                    <ilość_stron>300</ilość_stron>
                    <data_wydania dzień="04" miesiąc="04" rok="2014" />
                </książka>
                <książka id="010">
                    <tytuł>Jakaś książka 10</tytuł>
                    <autorzy> 
                        <autor nazwa_autora="Magdalena_Tulli"/>
                    </autorzy>
                    <ilość_stron>222</ilość_stron>
                    <data_wydania dzień="12" miesiąc="12" rok="2012" />
                </książka>
                <książka id="011">
                    <tytuł>Jakaś książka 11</tytuł>
                    <autorzy> 
                        <autor nazwa_autora="Magdalena_Tulli"/>
                        <autor nazwa_autora="Marek_Bieńczyk"/>
                    </autorzy>
                    <ilość_stron>458</ilość_stron>
                    <data_wydania dzień="13" miesiąc="01" rok="2016" />
                </książka>
            </książki>
        </dany_dział>
        
        <dany_dział id_działu="hr">
            <książki>
                <książka id="012">
                    <tytuł>Jakaś książka 12</tytuł>
                    <autorzy> 
                        <autor nazwa_autora="Paweł_Huelle"/>
                    </autorzy>
                    <ilość_stron>213</ilość_stron>
                    <data_wydania dzień="01" miesiąc="02" rok="2012" />
                </książka>
                <książka id="013">
                    <tytuł>Jakaś książka 13</tytuł>
                    <autorzy> 
                        <autor nazwa_autora="Paweł_Huelle"/>
                        <autor nazwa_autora="Marek_Bieńczyk"/>
                    </autorzy>
                    <ilość_stron>357</ilość_stron>
                    <data_wydania dzień="03" miesiąc="04" rok="2015" />
                </książka>
                <książka id="014">
                    <tytuł>Jakaś książka 14</tytuł>
                    <autorzy> 
                        <autor nazwa_autora="Michał_Witkowski"/>
                        <autor nazwa_autora="Marek_Bieńczyk"/>
                    </autorzy>
                    <ilość_stron>578</ilość_stron>
                    <data_wydania dzień="06" miesiąc="07" rok="2018" />
                </książka>
                <książka id="015">
                    <tytuł>Jakaś książka 15</tytuł>
                    <autorzy> 
                        <autor nazwa_autora="Paweł_Huelle"/>
                        <autor nazwa_autora="Michał_Witkowski"/>
                        <autor nazwa_autora="Jacek_Dukaj"/>
                    </autorzy>
                    <ilość_stron>777</ilość_stron>
                    <data_wydania dzień="09" miesiąc="11" rok="2013" />
                </książka>
                <książka id="016">
                    <tytuł>Jakaś książka 16</tytuł>
                    <autorzy> 
                        <autor nazwa_autora="Antoni_Libera"/>
                    </autorzy>
                    <ilość_stron>234</ilość_stron>
                    <data_wydania dzień="11" miesiąc="11" rok="2011" />
                </książka>
            </książki>
        </dany_dział>
        
        <dany_dział id_działu="bg">
            <książki>
                <książka id="017">
                    <tytuł>Jakaś książka 17</tytuł>
                    <autorzy> 
                        <autor nazwa_autora="Michał_Witkowski"/>
                    </autorzy>
                    <ilość_stron>150</ilość_stron>
                    <data_wydania dzień="12" miesiąc="11" rok="1999" />
                </książka>
            </książki>
        </dany_dział>
        
        <dany_dział id_działu="fn">
            <książki>
                <książka id="018">
                    <tytuł>Jakaś książka 18</tytuł>
                    <autorzy> 
                        <autor nazwa_autora="Jakub_Żulczyk"/>
                    </autorzy>
                    <ilość_stron>567</ilość_stron>
                    <data_wydania dzień="09" miesiąc="01" rok="2000" />
                </książka>
                <książka id="019">
                    <tytuł>Jakaś książka 19</tytuł>
                    <autorzy> 
                        <autor nazwa_autora="Jakub_Żulczyk"/>
                        <autor nazwa_autora="Wiesław_Myśliwski"/>
                    </autorzy>
                    <ilość_stron>765</ilość_stron>
                    <data_wydania dzień="01" miesiąc="11" rok="2001" />
                </książka>
                <książka id="020">
                    <tytuł>Jakaś książka 20</tytuł>
                    <autorzy> 
                        <autor nazwa_autora="Jakub_Żulczyk"/>
